run:
	docker compose up

background:
	docker compose up -d

build:
	docker compose build

buildup:
	docker compose up --build

logs:
	docker compose logs -ft

login:
	docker exec -it test-psql psql -U postgres

down:
	docker compose down -v
